# Generated by Django 5.1.4 on 2025-01-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('name', models.CharField(max_length=255, verbose_name="Iм'я")),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pizza', 'Піца'), ('drink', 'Напій'), ('sauce', 'Соус')], max_length=10, verbose_name='Категорія')),
                ('item_id', models.PositiveIntegerField(verbose_name='ID товару')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Напій')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('description', models.CharField(default='Опис відсутній', max_length=255, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drinks/')),
            ],
            options={
                'verbose_name': 'Напій',
                'verbose_name_plural': 'Напої',
            },
        ),
        migrations.CreateModel(
            name='PizzaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва піцци')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('description', models.CharField(default='Опис відсутній', max_length=255, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
            ],
            options={
                'verbose_name': 'Піцца',
                'verbose_name_plural': 'Піцци',
            },
        ),
        migrations.CreateModel(
            name='SauceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Соус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('description', models.CharField(default='Опис відсутній', max_length=255, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sauces/')),
            ],
            options={
                'verbose_name': 'Соус',
                'verbose_name_plural': 'Соуси',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='bot.botuser', verbose_name='Користувач')),
                ('items', models.ManyToManyField(related_name='carts', to='bot.cartitem', verbose_name='Товари')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('items', models.ManyToManyField(related_name='order_histories', to='bot.cartitem', verbose_name='Товари')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.botuser', verbose_name='Користувач')),
            ],
        ),
    ]
