# Generated by Django 5.1.4 on 2025-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_orderhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карта'), ('online', 'Онлайн оплата')], default='cash', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('paid for', 'Оплачено'), ('new', 'Новий'), ('pending', 'Очікує підтвердження'), ('preparing', 'Готується'), ('shipped', 'В дорозі'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
