# Generated by Django 5.1.4 on 2025-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_orderhistory_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
