# Generated by Django 5.1.4 on 2025-03-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_botuser_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адреса"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Iм'я")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Номер телефону",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="botuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="botuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="botuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="botuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ім'я"
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Прізвище"
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Юзернейм"
            ),
        ),
    ]
