# Generated by Django 5.1.4 on 2025-03-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_deliverydata_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverydata",
            options={
                "verbose_name": "Дані для доставки",
                "verbose_name_plural": "Дані для доставки",
            },
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="bot.cart",
                verbose_name="Корзина",
            ),
            preserve_default=False,
        ),
    ]
